[package]
name = "magiarecord_automatic_updater"
version = "0.1.0"
authors = ["wxf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.11.0"
reqwest = "0.9.22"
which = "3.1.0"
zip = "0.5.3"
